### ISSUE TITLE
Find a logo to use for Sponge

### ISSUE THREAD

**Issue by sk89q** [SpongePowered/Meta#3]
Currently the yellow "Sp" is a temporary logo.

**Comment by simon816** [comment]
Any news on this? Has been about 4 months and I hope the "Sp" is not going to stay.

**Comment by sk89q** [comment]
I asked an artist to help with the logo so we may use that.

There were a lot of submissions but I hate to say it, but most of them aren't quite logo quality.

**Comment by Dark-Arcana** [comment]
@sk89q 
Who did you ask? Can we get some mockups made in different styles and colors so we can get an idea of what we are looking for? Also can we get this person in a channel so we can talk to them? Are we going to be paying for these assets? If so we should work on getting some funds put together. We should really tackle this before a release to solidify our look and feel. Definitely need to have a solid look and feel for ore/forums/etc as well and the logo can really decide a lot of that in color and style.

**Comment by sk89q** [comment]
It's BigBadChris. I haven't received anything yet so it's still pending.

**Comment by Dark-Arcana** [comment]
Oh he makes really good stuff. He made my avatar <3. Still iffy about the whole Technic TPPI debacle.... so if he made anything he would need to express that he has no ownership or control over how we use or display assets that we acquire from him.

**Comment by lukegb** [comment]
Hooray!
